# Generated by Django 4.1.4 on 2022-12-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeName', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
    ]
